export const AUTHENTICATION_SERVICE_ENDPOINT = "http://localhost:5000"
export const GROUPING_SERVICE_ENDPOINT = "http://localhost:5001"
export const TIMEDELTA_SERVICE_ENDPOINT = "http://localhost:5002"
export const STORAGE_SERVICE_ENDPOINT = "http://localhost:5003"
export const STORAGE_SERVICE_API_KEY = "key-mobile-secret-789"
